name: energy model
log_dir: ./logs
chkpt_dir: ./checkpoints
save_best: True
batch_size: 128
load_checkpoint: False
dataset_path: ./dataset/
image_size: 32
channels: 3
out_dim: 1
lr : 0.001
buffer_size: 1024
algorithm: 0
alpha: 0.1
step_size: 10
steps: 60
max_epochs: 20
log_interval: 5
